import type { Metadata } from "next";
import { Balthazar } from "next/font/google";
import "./globals.css";

const balthazar = Balthazar({
  variable: "--font-balthazar",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${balthazar.variable}`}>
        {children}
      </body>
    </html>
  );
}
